export const moduleRoutes: Record<string, string> = {
  Dashboard: "/",
  Schools: "/schools",
  Ward: "/ward",
  "School Contacts": "/contacts",
  Enrollment: "/enrollment",
  Staff: "/staff",
  Infrastructure: "/infrastructure",
  Reports: "/reports",
  "Data Quality": "/data-quality",
  Exports: "/exports",
  "Users & Roles": "/users",
  "Audit Logs": "/audit-logs",
  "Backup & Restore": "/backup",
  Synchronization: "/synchronization",
  Settings: "/settings",
  "System Information": "/system-information",
};
