const accurateRabaiData = {
  dataset: {
    name: "Rabai Sub-County School Registry",
    county: "Kilifi",
    subCounty: "Rabai",
    dataYear: 2026,
    schemaVersion: "1.0.0",
    sourceStatus: "research_seed_dataset",
    notes: [
      "Official names have been preserved where the source lists a primary institution hosting JSS.",
      "JSS records are represented separately from the corresponding primary-school records.",
      "Null means that the information was not sufficiently verified from the searched online sources.",
      "SNE is YES only where a reliable source establishes special-needs learners; otherwise it is NO only where the school classification/source supports regular education, and UNKNOWN where verification was insufficient.",
      "Ward assignments should be treated as verified only where supported by the ward/source data.",
    ],
    counts: {
      publicPrimary: 48,
      privatePrimary: 14,
      publicJSS: 45,
      privateJSS: 1,
      publicSecondarySenior: 20,
      privateSecondarySenior: 0,
      totalRecords: 128,
    },
  },
  schools: [
    {
      id: "rabai-primary-001",
      officialName: "Bedida Primary School",
      displayName: "Bedida Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: null,
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-002",
      officialName: "Benyoka Primary School",
      displayName: "Benyoka Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: null,
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-003",
      officialName: "Bofu Primary School",
      displayName: "Bofu Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Bofu",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-004",
      officialName: "Boheka Primary School",
      displayName: "Boheka Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "Boheka",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-005",
      officialName: "Boyani Primary School",
      displayName: "Boyani Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Boyani",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-006",
      officialName: "Buni Primary School",
      displayName: "Buni Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Mazeras",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-007",
      officialName: "Bwagamoyo Primary School",
      displayName: "Bwagamoyo Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Bwagamoyo",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-008",
      officialName: "Chang'ombe Primary School",
      displayName: "Chang'ombe Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Chang'ombe",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-009",
      officialName: "Chiferi Primary School",
      displayName: "Chiferi Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Chiferi",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-010",
      officialName: "Chonyi Primary School",
      displayName: "Chonyi Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "Chonyi",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-011",
      officialName: "Gandani Primary School",
      displayName: "Gandani Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Gandani",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-012",
      officialName: "Isaac Nyondo",
      displayName: "Isaac Nyondo Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: null,
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-013",
      officialName: "Jeuri Primary School",
      displayName: "Jeuri Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Jeuri",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-014",
      officialName: "Jimba Primary School",
      displayName: "Jimba Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Jimba",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-015",
      officialName: "Kailo Primary School",
      displayName: "Kailo Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Kailo",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-016",
      officialName: "Kajiwe Primary School",
      displayName: "Kajiwe Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Kajiwe",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-017",
      officialName: "Kaliang'ombe Primary School",
      displayName: "Kaliang'ombe Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Kaliang'ombe",
      address: null,
      phone: "+254203318581",
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-018",
      officialName: "Kangakamo Primary School",
      displayName: "Kangakamo Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Kangakamo",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-019",
      officialName: "Kanyumbuni Pr",
      displayName: "Kanyumbuni Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Kanyumbuni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-020",
      officialName: "Kaoyeni Primary School",
      displayName: "Kaoyeni Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Kaoyeni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-021",
      officialName: "Kasidi Primary School",
      displayName: "Kasidi Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Kasidi",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-022",
      officialName: "Kawala Primary School",
      displayName: "Kawala Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Kawala",
      address: null,
      phone: "+254707715761",
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-023",
      officialName: "Kinung'una Primary School",
      displayName: "Kinung'una Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Kinung'una",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-024",
      officialName: "Lugwe Primary School",
      displayName: "Lugwe Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Lugwe",
      address: null,
      phone: "+254203318581",
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-025",
      officialName: "Maereni Primary School",
      displayName: "Maereni Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Maereni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-026",
      officialName: "Makanzani Primary School",
      displayName: "Makanzani Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Makanzani",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-027",
      officialName: "Makobeni Primary School",
      displayName: "Makobeni Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Makobeni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-028",
      officialName: "Malau Primary School",
      displayName: "Malau Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Malau",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-029",
      officialName: "Masaani Primary School",
      displayName: "Masaani Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "Masaani",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-030",
      officialName: "Mawe Mabomu Primary School",
      displayName: "Mawe Mabomu Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "Mawe Mabomu",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-031",
      officialName: "Mbungoni Primary School",
      displayName: "Mbungoni Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Mbungoni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-032",
      officialName: "Mbwaka Primary School",
      displayName: "Mbwaka Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "Mbwaka",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-033",
      officialName: "Mgalla Primary School",
      displayName: "Mgalla Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Mgalla",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-034",
      officialName: "Mikomani Primary School",
      displayName: "Mikomani Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Mikomani",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-035",
      officialName: "Mitsajeni Primary School",
      displayName: "Mitsajeni Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Mitsajeni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-036",
      officialName: "Muleji Primary School",
      displayName: "Muleji Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Muleji",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-037",
      officialName: "Mwandodo Primary School",
      displayName: "Mwandodo Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Mwandodo",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-038",
      officialName: "Mwangutwa Primary School",
      displayName: "Mwangutwa Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Mazeras",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-039",
      officialName: "Mwanjama Primary School",
      displayName: "Mwanjama Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Mwanjama",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-040",
      officialName: "Mwatsama Primary School",
      displayName: "Mwatsama Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Mwatsama",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-041",
      officialName: "Mwawesa Primary School",
      displayName: "Mwawesa Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Mwawesa",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-042",
      officialName: "Mwele Primary School",
      displayName: "Mwele Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Mwele",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-043",
      officialName: "Pangani Primary School",
      displayName: "Pangani Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Pangani",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-044",
      officialName: "Ribe Primary School",
      displayName: "Ribe Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Ribe",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-045",
      officialName: "St. Edwin",
      displayName: "St. Edwin",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: null,
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-046",
      officialName: "Timboni Primary School",
      displayName: "Timboni Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Timboni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-047",
      officialName: "Vifanjoni Primary School",
      displayName: "Vifanjoni Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Vifanjoni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-primary-048",
      officialName: "Ziro Primary School",
      displayName: "Ziro Primary School",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Ziro",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-private-primary-001",
      officialName: "Amani Junior",
      displayName: "Amani Junior",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PRIVATE",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "Mazeras",
      address: null,
      phone: "+254718540922",
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-private-primary-002",
      officialName: "Bridge International",
      displayName: "Bridge International",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PRIVATE",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: null,
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-private-primary-003",
      officialName: "Eddepa Junior",
      displayName: "Eddepa Junior",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PRIVATE",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: null,
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-private-primary-004",
      officialName: "Esemkei Shinning Star",
      displayName: "Esemkei Shinning Star",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PRIVATE",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: null,
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-private-primary-005",
      officialName: "Highway Academy Kokotoni",
      displayName: "Highway Academy Kokotoni",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PRIVATE",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "Kokotoni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-private-primary-006",
      officialName: "Khadija Centre",
      displayName: "Khadija Centre",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PRIVATE",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: null,
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-private-primary-007",
      officialName: "Mazeras Better Brains Academy",
      displayName: "Mazeras Better Brains Academy",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PRIVATE",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "Mazeras",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-private-primary-008",
      officialName: "Princess Junior",
      displayName: "Princess Junior",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PRIVATE",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: null,
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-private-primary-009",
      officialName: "Rabai Junior",
      displayName: "Rabai Junior",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PRIVATE",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "Mazeras",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-private-primary-010",
      officialName: "Riperbi Academy",
      displayName: "Riperbi Academy",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PRIVATE",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: null,
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-private-primary-011",
      officialName: "Ruruma Rising Stars",
      displayName: "Ruruma Rising Stars",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PRIVATE",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Ruruma",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-private-primary-012",
      officialName: "St. Charles Junior Academy Mazera's",
      displayName: "St. Charles Junior Academy Mazera's",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PRIVATE",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "Mazeras",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-private-primary-013",
      officialName: "St. Jude Academy",
      displayName: "St. Jude Academy",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PRIVATE",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: null,
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-private-primary-014",
      officialName: "Thomas Wakefield",
      displayName: "Thomas Wakefield",
      schoolCode: null,
      institutionType: "PRIMARY",
      sourceInstitutionType: null,
      ownership: "PRIVATE",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: null,
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-001",
      officialName: "Bedida Junior Secondary School",
      displayName: "Bedida Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Bedida",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-002",
      officialName: "Benyoka Primary School",
      displayName: "Benyoka Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Benyoka",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-003",
      officialName: "Bofu Primary School",
      displayName: "Bofu Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Bofu",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-004",
      officialName: "Boheka Primary School",
      displayName: "Boheka Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "Boheka",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-005",
      officialName: "Boyani Primary School",
      displayName: "Boyani Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Boyani",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-006",
      officialName: "Buni Primary School",
      displayName: "Buni Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Mazeras",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-007",
      officialName: "Bwagamoyo Primary School",
      displayName: "Bwagamoyo Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Bwagamoyo",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-008",
      officialName: "Chango'mbe Primary School",
      displayName: "Chang'ombe Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Chang'ombe",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-009",
      officialName: "Chhiferi Primary School",
      displayName: "Chiferi Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Chiferi",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-010",
      officialName: "Chonyi Primary School",
      displayName: "Chonyi Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "Chonyi",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-011",
      officialName: "Gandani Primary School",
      displayName: "Gandani Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Gandani",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-012",
      officialName: "Isaac Nyondo Primary School",
      displayName: "Isaac Nyondo Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: null,
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-013",
      officialName: "Jeuri Primary School",
      displayName: "Jeuri Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Jeuri",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-014",
      officialName: "Jimba Primary School",
      displayName: "Jimba Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Jimba",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-015",
      officialName: "Kailo Primary School",
      displayName: "Kailo Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Kailo",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-016",
      officialName: "Kajiwe Primary School",
      displayName: "Kajiwe Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Kajiwe",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-017",
      officialName: "Kaliang'mbe Primary School",
      displayName: "Kaliang'ombe Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Kaliang'ombe",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-018",
      officialName: "Kangamako Primary School",
      displayName: "Kangamako Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Kangakamo",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-019",
      officialName: "Kanyumbuni Primary School",
      displayName: "Kanyumbuni Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Kanyumbuni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-020",
      officialName: "Kaoyeni Primary School",
      displayName: "Kaoyeni Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Kaoyeni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-021",
      officialName: "Kasidi Primary School",
      displayName: "Kasidi Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Kasidi",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-022",
      officialName: "Kawala Primary School",
      displayName: "Kawala Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Kawala",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-023",
      officialName: "Kinung'una Primary School",
      displayName: "Kinung'una Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Kinung'una",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-024",
      officialName: "Lugwe Primary School",
      displayName: "Lugwe Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Lugwe",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-025",
      officialName: "M'bungoni Junior Secondary School",
      displayName: "M'bungoni Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "M'bungoni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-026",
      officialName: "M'bwaka Primary School",
      displayName: "M'bwaka Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "M'bwaka",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-027",
      officialName: "Maereni Primary School",
      displayName: "Maereni Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Maereni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-028",
      officialName: "Makanzani Primary School",
      displayName: "Makanzani Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Makanzani",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-029",
      officialName: "Makobeni Primary School",
      displayName: "Makobeni Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Makobeni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-030",
      officialName: "Malau Primary School",
      displayName: "Malau Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Malau",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-031",
      officialName: "Masaani Junior Secondary School",
      displayName: "Masaani Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "Masaani",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-032",
      officialName: "Mawe Mabomu Junior Secondary School",
      displayName: "Mawe Mabomu Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "Mawe Mabomu",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-033",
      officialName: "Mikomani Junior Secondary School",
      displayName: "Mikomani Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Mikomani",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-034",
      officialName: "Mitsajeni Primary School",
      displayName: "Mitsajeni Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Mitsajeni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-035",
      officialName: "Muleji Primary School",
      displayName: "Muleji Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Muleji",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-036",
      officialName: "Mwandodo Primary School",
      displayName: "Mwandodo Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Mwandodo",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-037",
      officialName: "Mwangutwa Primary School",
      displayName: "Mwangutwa Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Mazeras",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-038",
      officialName: "Mwanjama Primary School",
      displayName: "Mwanjama Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Mwanjama",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-039",
      officialName: "Mwatsama Primary School",
      displayName: "Mwatsama Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Mwatsama",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-040",
      officialName: "Mwele Primary School",
      displayName: "Mwele Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Mwele",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-041",
      officialName: "Pangani Primary School",
      displayName: "Pangani Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Pangani",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-042",
      officialName: "Ribe Junior Secondary School",
      displayName: "Ribe Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: null,
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Ribe",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-043",
      officialName: "Timboni Primary School",
      displayName: "Timboni Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Timboni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-044",
      officialName: "Vifanjoni Primary School",
      displayName: "Vifanjoni Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Vifanjoni",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-045",
      officialName: "Ziro Primary School",
      displayName: "Ziro Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Ziro",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-jss-private-001",
      officialName: "Esemkei Shining Star",
      displayName: "Esemkei Shining Star Junior Secondary School",
      schoolCode: null,
      institutionType: "JSS",
      sourceInstitutionType: "PRIMARY",
      ownership: "PRIVATE",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: null,
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-secondary-001",
      officialName: "Bofu Secondary School",
      displayName: "Bofu Senior School",
      schoolCode: "4122109",
      uicCode: "L6UA",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Bofu",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-002",
      officialName: "Bwagamoyo Secondary School",
      displayName: "Bwagamoyo Senior School",
      schoolCode: "4122117",
      uicCode: "3GBT",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Bwagamoyo",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-003",
      officialName: "Chang'ombe Secondary School",
      displayName: "Chang'ombe Senior School",
      schoolCode: "4122108",
      uicCode: "5EJR",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Chang'ombe",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-004",
      officialName: "Chiferi Secondary School",
      displayName: "Chiferi Senior School",
      schoolCode: "4122119",
      uicCode: "YM93",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Mwawesa",
      location: "Chiferi",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-005",
      officialName: "Dr Krapf Secondary School",
      displayName: "Dr. Krapf Senior School",
      schoolCode: "4122102",
      uicCode: "CALY",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "BOYS",
      boardingType: "BOARDING",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "Rabai",
      address: "Museum Road, Rabai",
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-006",
      officialName: "Jimba Secondary School",
      displayName: "Jimba Senior School",
      schoolCode: "4122112",
      uicCode: "9NS7",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Jimba",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-007",
      officialName: "Kajiwe Secondary School",
      displayName: "Kajiwe Senior School",
      schoolCode: "4122110",
      uicCode: "N3Q4",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Kajiwe",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-008",
      officialName: "Kambe Secondary School",
      displayName: "Kambe Senior School",
      schoolCode: "4122106",
      uicCode: "KGFR",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Kambe",
      address: null,
      phone: "728734451",
      email: "kambeseco@gmail.com",
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-009",
      officialName: "Kamoti Secondary School",
      displayName: "Kamoti Senior School",
      schoolCode: "4122120",
      uicCode: "T4SS",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Rabai",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-010",
      officialName: "Kasidi Secondary School",
      displayName: "Kasidi Senior School",
      schoolCode: "4122104",
      uicCode: "UR4F",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Kasidi",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-011",
      officialName: "Kawala Mixed Secondary School",
      displayName: "Kawala Mixed Senior School",
      schoolCode: "4122118",
      uicCode: "S7E5",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Kawala",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-012",
      officialName: "Kombeni Secondary School",
      displayName: "Kombeni Senior School",
      schoolCode: "4122103",
      uicCode: "XKHE",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "GIRLS",
      boardingType: "BOARDING",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: null,
      location: "Rabai",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-013",
      officialName: "Mbararani Secondary School",
      displayName: "Mbararani Senior School",
      schoolCode: "4122114",
      uicCode: "K58Y",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Mbararani",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-014",
      officialName: "Mikahani Secondary School",
      displayName: "Mikahani Senior School",
      schoolCode: "4122111",
      uicCode: "BNQA",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Mikahani",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-015",
      officialName: "Mikomani Secondary School",
      displayName: "Mikomani Senior School",
      schoolCode: "4122116",
      uicCode: "2WBS",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Ruruma",
      location: "Mikomani",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-016",
      officialName: "Mwandodo Secondary School",
      displayName: "Mwandodo Senior School",
      schoolCode: "4122115",
      uicCode: "RR7X",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Mwandodo",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-017",
      officialName: "Rabai Secondary School",
      displayName: "Rabai Senior School",
      schoolCode: "4122107",
      uicCode: "GU2J",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Mazeras/Rabai",
      address: "Mazeras, Rabai",
      phone: "+2541133559145",
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-018",
      officialName: "Rev Canon Kuri Memorial Secondary School",
      displayName: "Rev. Canon Kuri Memorial Senior School",
      schoolCode: "4122113",
      uicCode: "FSRM",
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "MIXED",
      boardingType: "DAY",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Rabai/Kisurutini",
      location: "Rabai",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "NO",
    },
    {
      id: "rabai-secondary-019",
      officialName: "Ribe Boys Secondary School",
      displayName: "Ribe Boys Senior School",
      schoolCode: null,
      uicCode: null,
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "BOYS",
      boardingType: "BOARDING",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Ribe",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
    {
      id: "rabai-secondary-020",
      officialName: "Ribe Girls Secondary School",
      displayName: "Ribe Girls Senior School",
      schoolCode: null,
      uicCode: null,
      institutionType: "SENIOR",
      sourceInstitutionType: "SECONDARY",
      ownership: "PUBLIC",
      gender: "GIRLS",
      boardingType: "BOARDING",
      county: "Kilifi",
      subCounty: "Rabai",
      ward: "Kambe/Ribe",
      location: "Ribe",
      address: null,
      phone: null,
      email: null,
      latitude: null,
      longitude: null,
      sne: "UNKNOWN",
    },
  ],
} as const;

export default accurateRabaiData;
